# Use the official httpd image as the base
FROM httpd:2.4

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip perl cpanminus

# Install CGI module using cpanm
RUN cpanm CGI

# Install Jinja2 with the specified flag
RUN pip3 install Jinja2 --break-system-packages

# Install BeautifulSoup with the specified flag
RUN pip3 install beautifulsoup4 --break-system-packages

# Set the working directory
WORKDIR /usr/local/apache2/public_html/

# Create a symbolic link to set up 'python' as an alias for 'python3'
RUN ln -s /usr/bin/python3 /usr/bin/python

# Copy the Apache configuration file
COPY httpd.conf /usr/local/apache2/conf/httpd.conf

# Enable CGI module in Apache
RUN sed -i 's/#LoadModule cgid_module/LoadModule cgid_module/' /usr/local/apache2/conf/httpd.conf

# Expose port 80
EXPOSE 80

# Start Apache in the foreground
CMD ["httpd-foreground"]
